spring:
  kafka:
#    bootstrap-servers: localhost:9092   # Kafka broker addresses
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer    # Serializer for the key
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Serializer for the value (event)
      acks: all  # Ensure all replicas acknowledge the message
      retries: 3 # Number of retries in case of a failure
      batch-size: 16384   # Batch size in bytes
      linger-ms: 1        # Time to wait before sending a batch
      buffer-memory: 33554432 # Buffer size in memory
    properties:
      security.protocol: PLAINTEXT  # Define the security protocol (PLAINTEXT or SSL)
    template:
      default-topic: order-events   # Default topic for producer
  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS}
    port: ${SPRING_CASSANDRA_PORT}
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE}
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
  application:
    name: order-service


#order:
#  event:
#    topicName: order-events

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
server:
  port: ${SERVER_PORT}

resilience4j.circuitbreaker:
  instances:
    createOrder:
      failureRateThreshold: 50  # Open circuit when 50% of requests fail
      slowCallRateThreshold: 60  # Open circuit if 60% of calls are slow
      slowCallDurationThreshold: 2s  # Calls taking more than 2 seconds are considered slow
      waitDurationInOpenState: 5s  # Time before Circuit Breaker moves to half-open state
      permittedNumberOfCallsInHalfOpenState: 3  # Number of calls allowed in half-open state
      maxWaitDurationInHalfOpenState: 2s  # Wait time in half-open state
      slidingWindowType: COUNT_BASED  # COUNT_BASED or TIME_BASED
      slidingWindowSize: 10  # Number of calls to monitor for Circuit Breaker state
      ignoreExceptions:
        - com.chuwa.orderservice.exception.EmptyCartException
        - com.chuwa.orderservice.exception.ResourceNotFoundException
        - com.chuwa.orderservice.exception.InsufficientStockException
