spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS}
    port: ${SPRING_CASSANDRA_PORT}
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE}
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
  application:
    name: order-service


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
server:
  port: ${SERVER_PORT}

resilience4j.circuitbreaker:
  instances:
    createOrder:
      failureRateThreshold: 50  # Open circuit when 50% of requests fail
      slowCallRateThreshold: 60  # Open circuit if 60% of calls are slow
      slowCallDurationThreshold: 2s  # Calls taking more than 2 seconds are considered slow
      waitDurationInOpenState: 5s  # Time before Circuit Breaker moves to half-open state
      permittedNumberOfCallsInHalfOpenState: 3  # Number of calls allowed in half-open state
      maxWaitDurationInHalfOpenState: 2s  # Wait time in half-open state
      slidingWindowType: COUNT_BASED  # COUNT_BASED or TIME_BASED
      slidingWindowSize: 10  # Number of calls to monitor for Circuit Breaker state
      ignoreExceptions:
        - com.chuwa.orderservice.exception.EmptyCartException
        - com.chuwa.orderservice.exception.ResourceNotFoundException
        - com.chuwa.orderservice.exception.InsufficientStockException
