
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/emart?useSSL=false&serverTimezone=UTC
    username: root
    password: ying1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    log-resolved-exception: true

server:
  port: 8080