spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}


server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

resilience4j.circuitbreaker:
  instances:
    itemService:
      failureRateThreshold: 50  # Open circuit when 50% of requests fail
      slowCallRateThreshold: 60  # Open circuit if 60% of calls are slow
      slowCallDurationThreshold: 2s  # Calls taking more than 2 seconds are considered slow
      waitDurationInOpenState: 5s  # Time before Circuit Breaker moves to half-open state
      permittedNumberOfCallsInHalfOpenState: 3  # Number of calls allowed in half-open state
      maxWaitDurationInHalfOpenState: 2s  # Wait time in half-open state
      slidingWindowType: COUNT_BASED  # COUNT_BASED or TIME_BASED
      slidingWindowSize: 10  # Number of calls to monitor for Circuit Breaker state
      ignoreExceptions:
        - com.chuwa.cartservice.exception.ResourceNotFoundException # Ignore 404 errors
