
spring:
  application:
    name: item-service


  mvc:
    log-resolved-exception: true
  data:
    mongodb:
      uri: mongodb+srv://eshen-impl:2q9b81KeQcQTfF4Z@bot5500.rjdhhhq.mongodb.net/emart-item?retryWrites=true&w=majority&appName=Bot5500

server:
  port: 8081
